

select
    loan_id,
    reporting_month,
    current_actual_upb,
    delinquency_status_code,
    delinquency_bucket,
    loan_age_months,
    remaining_months_to_legal_maturity,
    repurchase_flag,
    modification_flag,
    zero_balance_code,
    zero_balance_effective_date,
    current_interest_rate,
    current_deferred_upb,
    due_date_last_paid_installment,
    estimated_loan_to_value,
    zero_balance_removal_upb,
    delinquent_accrued_interest,
    delinquency_due_to_disaster,
    borrower_assistance_plan,
    current_month_modification_cost,
    interest_bearing_upb,
    prior_current_actual_upb,
    prior_delinquency_status_code,
    prior_delinquency_bucket,
    first_payment_date,
    maturity_date,
    credit_score,
    original_upb,
    original_interest_rate,
    original_ltv,
    original_cltv,
    original_dti,
    original_loan_term_months,
    loan_purpose,
    property_state,
    property_type,
    occupancy_status,
    channel,
    seller_name,
    servicer_name,
    source_year,
    source_quarter,
    case when zero_balance_code is null then true else false end as is_active
from "neondb"."analytics_int_mortgage"."int_loan_monthly_snapshot"