CREATE SCHEMA IF NOT EXISTS raw_freddie;

CREATE TABLE IF NOT EXISTS raw_freddie.origination_raw (
    credit_score TEXT,
    first_payment_date TEXT,
    first_time_homebuyer_flag TEXT,
    maturity_date TEXT,
    msa_md_code TEXT,
    mortgage_insurance_percentage TEXT,
    number_of_units TEXT,
    occupancy_status TEXT,
    original_cltv TEXT,
    original_dti TEXT,
    original_upb TEXT,
    original_ltv TEXT,
    original_interest_rate TEXT,
    channel TEXT,
    ppm_flag TEXT,
    product_type TEXT,
    property_state TEXT,
    property_type TEXT,
    postal_code TEXT,
    loan_sequence_number TEXT,
    loan_purpose TEXT,
    original_loan_term TEXT,
    number_of_borrowers TEXT,
    seller_name TEXT,
    servicer_name TEXT,
    super_conforming_flag TEXT,
    preharp_loan_identifier TEXT,
    harp_loan_indicator TEXT,
    program_indicator TEXT,
    property_valuation_method TEXT,
    interest_only_indicator TEXT,
    mortgage_insurance_cancellation_indicator TEXT,
    source_year SMALLINT NOT NULL,
    source_quarter SMALLINT NOT NULL,
    source_file_name TEXT NOT NULL,
    source_folder TEXT NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS raw_freddie.monthly_performance_raw (
    loan_sequence_number TEXT,
    monthly_reporting_period TEXT,
    current_actual_upb TEXT,
    current_loan_delinquency_status TEXT,
    loan_age TEXT,
    remaining_months_to_legal_maturity TEXT,
    repurchase_flag TEXT,
    modification_flag TEXT,
    zero_balance_code TEXT,
    zero_balance_effective_date TEXT,
    current_interest_rate TEXT,
    current_deferred_upb TEXT,
    due_date_last_paid_installment TEXT,
    mi_recoveries TEXT,
    net_sales_proceeds TEXT,
    non_mi_recoveries TEXT,
    expenses TEXT,
    legal_costs TEXT,
    maintenance_preservation_costs TEXT,
    taxes_and_insurance TEXT,
    miscellaneous_expenses TEXT,
    actual_loss_calculation TEXT,
    modification_cost TEXT,
    step_modification_flag TEXT,
    deferred_payment_plan TEXT,
    estimated_loan_to_value TEXT,
    zero_balance_removal_upb TEXT,
    delinquent_accrued_interest TEXT,
    delinquency_due_to_disaster TEXT,
    borrower_assistance_plan TEXT,
    current_month_modification_cost TEXT,
    interest_bearing_upb TEXT,
    source_year SMALLINT NOT NULL,
    source_quarter SMALLINT NOT NULL,
    source_file_name TEXT NOT NULL,
    source_folder TEXT NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
